package com.topfreegames.bikerace;

/* JADX INFO: compiled from: MainConfig.java */
/* JADX INFO: loaded from: /home/francisco/bike_race/apk/classes.dex */
enum av {
    DEBUG_FREE_SINGLE_GOOGLE_REVIEW,
    DEBUG_FREE_SINGLE_GOOGLE_PLAY,
    DEBUG_FREE_MULTI_GOOGLE_REVIEW,
    DEBUG_FREE_MULTI_GOOGLE_PLAY,
    DEBUG_FREE_SINGLE_AMAZON,
    DEBUG_FREE_MULTI_AMAZON,
    DEBUG_FREE_MULTI_SAMSUNG,
    DEBUG_FREE_SINGLE_BLACKBERRY,
    DEBUG_PRO_SINGLE_GOOGLE_REVIEW,
    DEBUG_PRO_SINGLE_GOOGLE_PLAY,
    DEBUG_PRO_MULTI_GOOGLE_REVIEW,
    DEBUG_PRO_MULTI_GOOGLE_PLAY,
    DEBUG_PRO_SINGLE_AMAZON,
    DEBUG_PRO_MULTI_AMAZON,
    DEBUG_PRO_SINGLE_BLACKBERRY,
    RELEASE_FREE_SINGLE_GOOGLE_REVIEW,
    RELEASE_FREE_SINGLE_GOOGLE_PLAY,
    RELEASE_FREE_MULTI_GOOGLE_REVIEW,
    RELEASE_FREE_MULTI_GOOGLE_PLAY,
    RELEASE_FREE_SINGLE_AMAZON,
    RELEASE_FREE_MULTI_AMAZON,
    RELEASE_FREE_SINGLE_BLACKBERRY,
    RELEASE_FREE_MULTI_SAMSUNG,
    RELEASE_PRO_SINGLE_GOOGLE_REVIEW,
    RELEASE_PRO_SINGLE_GOOGLE_PLAY,
    RELEASE_PRO_MULTI_GOOGLE_REVIEW,
    RELEASE_PRO_MULTI_GOOGLE_PLAY,
    RELEASE_PRO_SINGLE_AMAZON,
    RELEASE_PRO_MULTI_AMAZON,
    RELEASE_PRO_SINGLE_BLACKBERRY;

    /* JADX INFO: renamed from: values, reason: to resolve conflict with enum method */
    public static av[] valuesCustom() {
        av[] avVarArrValuesCustom = values();
        int length = avVarArrValuesCustom.length;
        av[] avVarArr = new av[length];
        System.arraycopy(avVarArrValuesCustom, 0, avVarArr, 0, length);
        return avVarArr;
    }
}
